routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([], function () {
    Route::match(['get', 'post'], '/', ['uses' => 'IndexController@execute', 'as' => 'home']);
    Route::get('/page/{alias}', ['uses' => 'PageController@execute', 'as' => 'page']);
    Route::auth();
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', function () {
        if (view()->exists('admin.index')) {
            $data['title'] = 'Панель администратора';
            return view('admin.index')->with($data);
        }
    });
    Route::resources([
        'pages' => 'PagesController',
        'services' => 'ServicesController',
        'portfolios' => 'PortfoliosController',
    ]);

});

resources/views/admin/content_pages.blade.php
<div class="container">
    @if($pages)
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Имя</th>
                <th>Псевдоним</th>
                <th>Текст</th>
                <th>Дата создания</th>
                <th>Удалить</th>
            </tr>
            </thead>
            <tbody>
            @foreach($pages as $k => $page)
                <tr>
                    <td>{{ $page->id }}</td>
                    <td>{!! Html::link(route('pages.edit',$page), $page->name, ['alt' => $page->name]) !!}</td>
                    <td>{{ $page->alias }}</td>
                    <td>{{ $page->text }}</td>
                    <td>{{ $page->created_at }}</td>
                    <td>
                        {!! Form::open(['url'=>route('pages.destroy',$page), 'class'=>'form-horizontal', 'method' => 'POST']) !!}
                        {{--name=action value=delete--}}
                        {!! Form::hidden('_method', 'delete') !!}
                        {{--value , --}}
                        {!! Form::button('Удалить', ['class' => 'btn btn-danger', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
    {!! Html::link(route('pages.create'), 'Новая страница', ['class' => 'btn btn-success']) !!}
</div>

resources/views/admin/content_pages_create.blade.php
<div class="container">
    {!! Form::open(['url'=>route('pages.store'), 'class'=>'form-horizontal', 'method' => 'POST', 'enctype' => 'multipart/form-data']) !!}
    <div class="form-group">
        {!! Form::label('name', 'Название', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => 'Введите название страницы']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('alias', 'Псевдоним', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            {!! Form::text('alias', old('alias'), ['class' => 'form-control', 'placeholder' => 'Введите псведоним страницы']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('text', 'Текст', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            <textarea name="text" id="editor" cols="30" rows="10" class="form-control" placeholder='Введите текств страницы'></textarea>
{{--            {!! Form::text('text', old('text'), ['id' => 'editor', 'class' => 'form-control', 'placeholder' => 'Введите текств страницы']) !!}--}}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('images', 'Изображение:',['class'=>'col-xs-2 control-label']) !!}
        <div class="col-xs-8">
            {!! Form::file('images', ['class' => 'filestyle','data-buttonText'=>'Выберите изображение','data-buttonName'=>"btn-primary",'data-placeholder'=>"Файла нет"]) !!}
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            {!! Form::button('Сохранить', ['class' => 'btn btn-primary','type'=>'submit']) !!}
        </div>
    </div>

    {!! Form::close() !!}


</div>
<script>
    $(document).ready(function () {
        CKEDITOR.replace('editor');
    });
</script>

resources/views/admin/content_pages_edit.blade.php
<div class="container">
    {!! Form::open(['url'=>route('pages.update',$page), 'class'=>'form-horizontal', 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}
    <div class="form-group">
        {!! Form::label('name', 'Название', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            {!! Form::text('name', $page->name, ['class' => 'form-control', 'placeholder' => 'Введите название страницы']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('alias', 'Псевдоним', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            {!! Form::text('alias', $page->alias, ['class' => 'form-control', 'placeholder' => 'Введите псведоним страницы']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('text', 'Текст', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            <textarea name="text" id="editor" cols="30" rows="10" class="form-control" placeholder='Введите текств страницы'>{{ $page->text }}</textarea>
            {{--            {!! Form::text('text', old('text'), ['id' => 'editor', 'class' => 'form-control', 'placeholder' => 'Введите текств страницы']) !!}--}}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('old_images', 'Старое изображение:',['class'=>'col-xs-2 control-label']) !!}
        <div class="col-xs-8">
            {!! Html::image('assets/img/'.$page->images, '', ['class'=>'img-circle img-responsive','width'=>'150px']) !!}
            {!! Form::hidden('old_images', $page->images) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('images', 'Обновить изображение:',['class'=>'col-xs-2 control-label']) !!}
        <div class="col-xs-8">
            {!! Form::file('images', ['class' => 'filestyle','data-buttonText'=>'Выберите изображение','data-buttonName'=>"btn-primary",'data-placeholder'=>"Файла нет"]) !!}
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            {!! Form::button('Обновить', ['class' => 'btn btn-primary','type'=>'submit']) !!}
        </div>
    </div>

    {!! Form::close() !!}


</div>
<script>
    $(document).ready(function () {
        CKEDITOR.replace('editor');
    });
</script>

resources/views/admin/content_portfolios.blade.php
<div class="container">
    @if($portfolios)
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Имя</th>
                <th>Фильтр</th>
                <th>Дата создания</th>
                <th>Удалить</th>
            </tr>
            </thead>
            <tbody>
            @foreach($portfolios as $k => $portfolio)
                <tr>
                    <td>{{ $portfolio->id }}</td>
                    <td>{!! Html::link(route('portfolios.edit',$portfolio), $portfolio->name, ['alt' => $portfolio->name]) !!}</td>
                    <td>{{ $portfolio->filter }}</td>
                    <td>{{ $portfolio->created_at }}</td>
                    <td>
                        {!! Form::open(['url'=>route('portfolios.destroy',$portfolio), 'class'=>'form-horizontal', 'method' => 'POST']) !!}
                        {{--name=action value=delete--}}
                        {!! Form::hidden('_method', 'delete') !!}
                        {{--value , --}}
                        {!! Form::button('Удалить', ['class' => 'btn btn-danger', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
    {!! Html::link(route('portfolios.create'), 'Новая запись', ['class' => 'btn btn-success']) !!}
</div>

resources/views/admin/content_portfolios_create.blade.php
<div class="container">
    {!! Form::open(['url'=>route('portfolios.store'), 'class'=>'form-horizontal', 'method' => 'POST', 'enctype' => 'multipart/form-data']) !!}
    <div class="form-group">
        {!! Form::label('name', 'Название', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => 'Введите название страницы']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('filter', 'Фильтр', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            {!! Form::text('filter', old('filter'), ['class' => 'form-control', 'placeholder' => 'Введите название страницы']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('images', 'Изображение:',['class'=>'col-xs-2 control-label']) !!}
        <div class="col-xs-8">
            {!! Form::file('images', ['class' => 'filestyle','data-buttonText'=>'Выберите изображение','data-buttonName'=>"btn-primary",'data-placeholder'=>"Файла нет"]) !!}
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            {!! Form::button('Сохранить', ['class' => 'btn btn-primary','type'=>'submit']) !!}
        </div>
    </div>

    {!! Form::close() !!}


</div>
<script>
    $(document).ready(function () {
        CKEDITOR.replace('editor');
    });
</script>

resources/views/admin/content_portfolios_edit.blade.php
<div class="container">
    {!! Form::open(['url'=>route('portfolios.update', $portfolio), 'class'=>'form-horizontal', 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}
    <div class="form-group">
        {!! Form::label('name', 'Название', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            {!! Form::text('name', $portfolio->name, ['class' => 'form-control', 'placeholder' => 'Введите название страницы']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('filter', 'Фильтр', ['class' => 'col-xs-2 control-label']) !!}
        <div class="col-zs-8">
            {{--name, value хелпер old--}}
            {!! Form::text('filter', $portfolio->filter, ['class' => 'form-control', 'placeholder' => 'Введите название страницы']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('old_images', 'Старое изображение:',['class'=>'col-xs-2 control-label']) !!}
        <div class="col-xs-8">
            {!! Html::image('assets/img/'.$portfolio->images, '', ['class'=>'img-circle img-responsive','width'=>'150px'] ) !!}
            {!! Form::hidden('old_images', $portfolio->images) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('images', 'Обновить изображение:',['class'=>'col-xs-2 control-label']) !!}
        <div class="col-xs-8">
            {!! Form::file('images', ['class' => 'filestyle','data-buttonText'=>'Выберите изображение','data-buttonName'=>"btn-primary",'data-placeholder'=>"Файла нет"]) !!}
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            {!! Form::button('Обновить', ['class' => 'btn btn-primary','type'=>'submit']) !!}
        </div>
    </div>

    {!! Form::close() !!}


</div>
<script>
    $(document).ready(function () {
        CKEDITOR.replace('editor');
    });
</script>

resources/views/admin/header.blade.php
<!-- Container -->
<div class="portfolio">

    <div id="filters" class="sixteen columns">
        <ul style="padding:0px 0px 0px 0px">
            <li><a href="{{route('pages.index')}}">
                    <h5>Страницы</h5>
                </a>
            </li>

            <li><a href="{{route('portfolios.index')}}">
                    <h5>Порфолио</h5>
                </a>
            </li>

            <li><a href="{{route('services.index')}}">
                    <h5>Сервисы</h5>
                </a>
            </li>
        </ul>
    </div>

</div>

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('header')

    @include('admin.header')

@endsection

resources/views/admin/pages.blade.php
@extends('layouts.admin')

@section('header')

    @include('admin.header')

@endsection

@section('content')

    @include('admin.content_pages')

@endsection

resources/views/admin/pages_create.blade.php
@extends('layouts.admin')

@section('header')

    @include('admin.header')

@endsection

@section('content')

    @include('admin.content_pages_create')

@endsection

resources/views/admin/pages_edit.blade.php
@extends('layouts.admin')

@section('header')

    @include('admin.header')

@endsection

@section('content')

    @include('admin.content_pages_edit')

@endsection

resources/views/admin/portfolios.blade.php
@extends('layouts.admin')

@section('header')

    @include('admin.header')

@endsection

@section('content')

    @include('admin.content_portfolios')

@endsection

resources/views/admin/portfolios_create.blade.php
@extends('layouts.admin')

@section('header')

    @include('admin.header')

@endsection

@section('content')

    @include('admin.content_portfolios_create')

@endsection

resources/views/admin/portfolios_edit.blade.php
@extends('layouts.admin')

@section('header')

    @include('admin.header')

@endsection

@section('content')

    @include('admin.content_portfolios_edit')

@endsection